services:
  mindfulbooks_db:
    image: postgres
    container_name: todo_app_db_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - todo_app_db:/var/lib/postgresql/data
volumes:
  todo_app_db:
